eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
server:
  port: 8080
spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://mongo:27017/product-service
  jpa:
    hibernate:
      ddl-auto: create
