spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  jpa:
    open-in-view: false

server:
  port: 8080
#  port: 0 todo: uncoment

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
